//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpRestApiClientKeystone.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpRestApiClientKeystone.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using System.Text.Json results in improved performances when compared with Newtonsoft.Json..
        /// </summary>
        internal static string AnalyzerDescription001 {
            get {
                return ResourceManager.GetString("AnalyzerDescription001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using intermediate strings during deserialization leads to poor performance and streams should be used instead..
        /// </summary>
        internal static string AnalyzerDescription002 {
            get {
                return ResourceManager.GetString("AnalyzerDescription002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use HttpClientFactory to create and reuse HttpClient.
        /// </summary>
        internal static string AnalyzerDescription004 {
            get {
                return ResourceManager.GetString("AnalyzerDescription004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using newtonsoft for JSON deserialization.
        /// </summary>
        internal static string AnalyzerMessageFormat001 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using strings for JSON deserialization.
        /// </summary>
        internal static string AnalyzerMessageFormat002 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid creating new instances of HttpClient for making Http calls to services..
        /// </summary>
        internal static string AnalyzerMessageFormat004 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newtonsoft used for JSON deserialization.
        /// </summary>
        internal static string AnalyzerTitle001 {
            get {
                return ResourceManager.GetString("AnalyzerTitle001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String used for JSON deserialization.
        /// </summary>
        internal static string AnalyzerTitle002 {
            get {
                return ResourceManager.GetString("AnalyzerTitle002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpClientFactory used for HttpClient creation.
        /// </summary>
        internal static string AnalyzerTitle004 {
            get {
                return ResourceManager.GetString("AnalyzerTitle004", resourceCulture);
            }
        }
    }
}
